package com.wms.service;

import com.lowagie.text.*;
import com.lowagie.text.Font;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import com.wms.entity.Report;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.stereotype.Service;

import java.awt.*;
import java.io.IOException;
import java.time.format.DateTimeFormatter;

@Service
public class PdfService {

    public void generateReportPdf(Report report, HttpServletResponse response) throws IOException {
        Document document = new Document(PageSize.A4);
        PdfWriter.getInstance(document, response.getOutputStream());

        document.open();

        // Fonts
        Font fontHeader = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 24, Color.DARK_GRAY);
        Font fontSubHeader = FontFactory.getFont(FontFactory.HELVETICA, 12, Color.GRAY);
        Font fontLabel = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, Color.BLACK);
        Font fontValue = FontFactory.getFont(FontFactory.HELVETICA, 12, Color.DARK_GRAY);
        Font fontContent = FontFactory.getFont(FontFactory.HELVETICA, 11, Color.BLACK);

        // Header Table
        PdfPTable headerTable = new PdfPTable(1);
        headerTable.setWidthPercentage(100);
        headerTable.setSpacingAfter(20);

        PdfPCell cell = new PdfPCell(new Phrase("WEDDING MANAGEMENT SYSTEM", fontHeader));
        cell.setBorder(com.lowagie.text.Rectangle.NO_BORDER);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        headerTable.addCell(cell);

        cell = new PdfPCell(new Phrase("Official Report Document", fontSubHeader));
        cell.setBorder(com.lowagie.text.Rectangle.NO_BORDER);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        headerTable.addCell(cell);

        document.add(headerTable);

        // Horizontal Line
        document.add(new Paragraph("______________________________________________________________________________"));
        document.add(new Paragraph(" "));

        // Report Info Table
        PdfPTable infoTable = new PdfPTable(2);
        infoTable.setWidthPercentage(100);
        infoTable.setWidths(new float[]{1.5f, 3.5f});
        infoTable.setSpacingAfter(20);

        addInfoRow(infoTable, "Report Title:", report.getTitle(), fontLabel, fontValue);
        addInfoRow(infoTable, "Report Type:", report.getType(), fontLabel, fontValue);
        addInfoRow(infoTable, "Generated By:", (report.getGeneratedBy() != null ? report.getGeneratedBy() : "Administrator"), fontLabel, fontValue);
        
        String dateStr = "N/A";
        if (report.getGeneratedDate() != null) {
            dateStr = report.getGeneratedDate().format(DateTimeFormatter.ofPattern("dd MMM yyyy, hh:mm a"));
        }
        addInfoRow(infoTable, "Date:", dateStr, fontLabel, fontValue);

        document.add(infoTable);

        // Content
        Paragraph contentTitle = new Paragraph("REPORT DETAILS:", fontLabel);
        contentTitle.setSpacingAfter(10);
        document.add(contentTitle);

        Paragraph contentBody = new Paragraph((report.getContent() != null ? report.getContent() : ""), fontContent);
        contentBody.setSpacingAfter(30);
        document.add(contentBody);

        // Footer
        document.add(new Paragraph(" "));
        document.add(new Paragraph("______________________________________________________________________________"));
        Paragraph footer = new Paragraph("This is an automatically generated document from WedLux Wedding Management System.", FontFactory.getFont(FontFactory.HELVETICA, 10, Color.GRAY));
        footer.setAlignment(Element.ALIGN_CENTER);
        document.add(footer);

        document.close();
    }

    public void generatePaymentSlipPdf(String bank, String txnId, String amount, String customerName, String email, HttpServletResponse response) throws IOException {
        Document document = new Document(PageSize.A4);
        PdfWriter.getInstance(document, response.getOutputStream());

        document.open();

        // Colors
        Color themeColor = new Color(75, 0, 130); // Indigo

        // Header
        Font fontTitle = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 26, themeColor);
        Paragraph title = new Paragraph("PAYMENT RECEIPT", fontTitle);
        title.setAlignment(Element.ALIGN_CENTER);
        document.add(title);

        Paragraph subTitle = new Paragraph("WedLux Wedding Management System", FontFactory.getFont(FontFactory.HELVETICA, 12, Color.GRAY));
        subTitle.setAlignment(Element.ALIGN_CENTER);
        subTitle.setSpacingAfter(30);
        document.add(subTitle);

        // Status Box
        PdfPTable statusTable = new PdfPTable(1);
        statusTable.setWidthPercentage(40);
        PdfPCell statusCell = new PdfPCell(new Phrase("Status: PAYMENT SUCCESSFUL", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, Color.WHITE)));
        statusCell.setBackgroundColor(new Color(40, 167, 69)); // Success Green
        statusCell.setPadding(10);
        statusCell.setHorizontalAlignment(Element.ALIGN_CENTER);
        statusCell.setBorder(com.lowagie.text.Rectangle.NO_BORDER);
        statusTable.addCell(statusCell);
        statusTable.setSpacingAfter(30);
        document.add(statusTable);

        // Details Table
        PdfPTable detailsTable = new PdfPTable(2);
        detailsTable.setWidthPercentage(100);
        detailsTable.setWidths(new float[]{2f, 3f});
        detailsTable.setSpacingBefore(10);
        
        Font labelFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, Color.BLACK);
        Font valueFont = FontFactory.getFont(FontFactory.HELVETICA, 12, Color.DARK_GRAY);

        // Section: Payment Details
        addSectionHeader(detailsTable, "Payment Information", themeColor);
        addInfoRow(detailsTable, "Transaction ID:", txnId, labelFont, valueFont);
        addInfoRow(detailsTable, "Payment Type:", "Net banking / Card", labelFont, valueFont);
        addInfoRow(detailsTable, "Bank Name:", bank, labelFont, valueFont);
        addInfoRow(detailsTable, "Amount Paid:", "LKR " + amount, labelFont, valueFont);
        
        // Spacer
        addEmptyRow(detailsTable);

        // Section: Customer Information
        addSectionHeader(detailsTable, "Customer Information", themeColor);
        addInfoRow(detailsTable, "Customer Name:", customerName, labelFont, valueFont);
        addInfoRow(detailsTable, "Email Address:", email, labelFont, valueFont);

        document.add(detailsTable);

        // Footer
        document.add(new Paragraph("\n\n\n"));
        document.add(new Paragraph("______________________________________________________________________________"));
        Paragraph footer = new Paragraph("Thank you for choosing WedLux. We look forward to making your wedding special!", FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 11, Color.DARK_GRAY));
        footer.setAlignment(Element.ALIGN_CENTER);
        footer.setSpacingBefore(10);
        document.add(footer);

        document.close();
    }

    private void addInfoRow(PdfPTable table, String label, String value, Font labelFont, Font valueFont) {
        PdfPCell cellLabel = new PdfPCell(new Phrase(label, labelFont));
        cellLabel.setBorder(com.lowagie.text.Rectangle.NO_BORDER);
        cellLabel.setPaddingBottom(8);
        table.addCell(cellLabel);

        PdfPCell cellValue = new PdfPCell(new Phrase(value != null ? value : "N/A", valueFont));
        cellValue.setBorder(com.lowagie.text.Rectangle.NO_BORDER);
        cellValue.setPaddingBottom(8);
        table.addCell(cellValue);
    }

    private void addSectionHeader(PdfPTable table, String title, Color color) {
        Font sectionFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, color);
        PdfPCell cell = new PdfPCell(new Phrase(title, sectionFont));
        cell.setColspan(2);
        cell.setBorder(com.lowagie.text.Rectangle.BOTTOM);
        cell.setBorderColor(color);
        cell.setPaddingBottom(5);
        table.addCell(cell);
        
        // Add a tiny spacer after header
        PdfPCell spacer = new PdfPCell(new Phrase(" "));
        spacer.setColspan(2);
        spacer.setBorder(com.lowagie.text.Rectangle.NO_BORDER);
        spacer.setFixedHeight(10);
        table.addCell(spacer);
    }
    
    private void addEmptyRow(PdfPTable table) {
        PdfPCell cell = new PdfPCell(new Phrase(" "));
        cell.setColspan(2);
        cell.setBorder(com.lowagie.text.Rectangle.NO_BORDER);
        cell.setFixedHeight(20);
        table.addCell(cell);
    }
}
